repos:
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.8.2
  hooks:
    - id: check-jsonschema
      name: "Validate JSON files against JSON Schemas"
      files: building_inputs/master_general_resources_database.json
      types: [json]
      args: ["--schemafile", "json_schemas/master_general_resources_database.json"]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black-jupyter
      additional_dependencies: ['click==8.0.4']
      name: "Lint Jupyter notebooks using Black"
      files: decision-support-tool.ipynb
- repo: https://github.com/mwouts/jupytext
  rev: v1.11.0
  hooks:
    - id: jupytext
      name: "Generate a .py file from the notebook"
      entry: jupytext --to py decision-support-tool.ipynb
      pass_filenames: false
