name: decision-support-tool
channels:
  - conda-forge 
dependencies:
  - panel
  - param
  - bokeh
  - holoviews
  - hvplot
  - geoviews
  - xarray
  - geoviews
  - cartopy
  - pyproj
  - pandas
  - numpy
  - matplotlib
  - jupyter-panel-proxy
  - pip:
    - datetime
    - xlrd
    - scikit-learn
