name: decision-support-tool
channels:
  - conda-forge 
dependencies:
  - panel
  - param
  - bokeh
  - holoviews
  - geoviews
  - xarray
  - hvplot
  - cartopy
  - pyproj
  - pandas
  - numpy
  - jupyter-panel-proxy
  - pip:
    - datetime
